#!/bin/bash -i

localbin="$HOME/.local/bin"
globalbin="/usr/local/bin"
bashrc="$HOME/.bashrc"
tmp="/tmp/tgpt"

## Install script for GNU/Linux & MacOS

set -e

echo -e "Installation type?\n1) System wide installation
2) User installation"
read -r bindir
if [ "$bindir" == "1" ]; then
	bindir="$globalbin"
	tgpt="${bindir}/tgpt"
elif [ "$bindir" == "2"  ]; then
	bindir="$localbin"
	tgpt="${bindir}/tgpt"
else
	echo -e "Wrong installation type, exiting..."
	exit 1
fi

# Check the system architecture
if [[ $(uname -m) == "x86_64" ]]; then
    ARCH="amd64"
elif [[ $(uname -m) == "i386" || $(uname -m) == "i686" ]]; then
    ARCH="i386"
elif [[ $(uname -m) == "arm64" ]]; then
    ARCH="arm64"
else
    echo "Unsupported architecture: $(uname -m)"
    exit 1
fi

# Check if the system is macOS
if [[ $(uname -s) == "Darwin" ]]; then
    OS="mac"
else
    OS="linux"
fi

echo "Operating System: ${OS}"
echo -e "Processor Architecture: ${ARCH}\n"
# Set the URL of the executable based on the architecture and OS
URL="https://github.com/aandrew-me/tgpt/releases/latest/download/tgpt-${OS}-${ARCH}"
# Download the executable
echo -e "Downloading...\n"
curl -sSL "$URL" -o  "$tmp"

if [ ! -d "$bindir" ]; then
	if [ "$bindir" == "$globalbin" ]; then
		echo -e "Creating ${bindir}..."
		sudo mkdir -p "$bindir"
	else
                echo -e "Creating ${bindir}..."
		mkdir -p "$bindir"
	fi
fi

# Move the executable to a directory in PATH (e.g. /usr/local/bin/ on Linux, /usr/local/bin/ or /usr/local/opt/ on macOS)
if [[ "$OS" == "linux" ]]; then
	if [ "$bindir" == "$globalbin" ]; then
		echo -e "Moving ${tmp} to ${bindir}..."
		sudo mv "$tmp" "$bindir"
 	else
		echo -e "Moving ${tmp} to ${bindir}..."
		mv "$tmp" "$bindir"
	fi
else
        if [ "$bindir" == "$globalbin" ]; then
		echo -e "Moving ${tmp} to ${bindir}..."
                sudo mv "$tmp" "$bindir"
        else
		echo -e "Moving ${tmp} to ${bindir}..."
                mv "$tmp" "$bindir"
        fi
fi

if [[ ":$PATH:" == *":$bindir:"* ]]; then
	echo -e "Your path is correctly set"
else
	echo -e "Your path is missing ${bindir}"
	if [[ "$SHELL" == "/bin/bash" && -f "$bashrc" ]]; then
cat << EOF >> "$bashrc"
export PATH="$bindir:$PATH"
EOF
	source "$bashrc"
	echo -e "Added ${bindir} to path"
	fi
fi

if [ -f "$tgpt" ]; then
	if [ "$bindir" == "$globalbin" ]; then
		echo -e "Making ${tgpt} executable..."
		sudo chmod +x "$tgpt"
	else
		echo -e "Making ${tgpt} executable..."
		chmod +x "$tgpt"
	fi
	if [ $(which tgpt) ]; then
		echo -e "Installed Successfully \n"
		if [ "$bindir" == "$globalbin" ]; then
		echo -e "Run tgpt -h to get started"
		else
		echo -e "Reload your terminal and run tgpt -h to get started"
		fi
	else
		echo -e "tgpt not found in ${bindir}"
	fi
else
	echo -e "there is no tgpt in ${bindir}"
fi

