#!/usr/bin/env bash


## Install script for GNU/Linux & MacOS

set -e
path=/usr/local/bin

if ! [ -z "$1" ]; then
    path=$1
fi

echo "Download location: $path"

if [ ! -w "$path" ]; then
    SUDO="sudo"
else
    SUDO=""
fi

# Check the system architecture
if [[ $(uname -m) == "x86_64" ]]; then
    ARCH="amd64"
elif [[ $(uname -m) == "i386" || $(uname -m) == "i686" ]]; then
    ARCH="i386"
elif [[ $(uname -m) == "arm64" || $(uname -m) == "aarch64" ]]; then
    ARCH="arm64"
else
    echo "Unsupported architecture: $(uname -m)"
    exit 1
fi

# Check if the system is macOS
if [[ $(uname -s) == "Darwin" ]]; then
    OS="mac"
else
    OS="linux"
fi

echo "Operating System: ${OS}"
echo -e "Processor Architecture: ${ARCH}\n"
# Set the URL of the executable based on the architecture and OS
URL="https://github.com/aandrew-me/tgpt/releases/latest/download/tgpt-${OS}-${ARCH}"
# Download the executable
echo -e "Downloading...\n"
curl -SL --progress-bar "$URL" -o /tmp/tgpt

# Move the executable to a directory in PATH (e.g. /usr/local/bin/ on Linux, /usr/local/bin/ or /usr/local/opt/ on macOS)
if [[ $OS == "linux" ]]; then
    $SUDO mv /tmp/tgpt $path
else
    $SUDO mv /tmp/tgpt $path
fi

if [ -d "$path" ]; then
    $SUDO chmod +x $path/tgpt
elif [ -f "$path" ]; then
    $SUDO chmod +x $path
fi

echo -e "Installed Successfully \n"

if [[ $path != "/usr/local/bin" ]]; then
echo "Make sure your file is in PATH"
echo "Then run tgpt -h to get started"
else
echo -e "Run tgpt -h to get started"
fi

